name: Create docker images

on:
  push:
    branches:
      - analytics

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate random hash
        id: random_hash
        run: echo "hash=$(openssl rand -hex 4)" >> $GITHUB_OUTPUT

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io
        with:
          image: umami
          tags: cloud-${{ steps.random_hash.outputs.hash }}, cloud-latest
          buildArgs: DATABASE_TYPE=postgresql
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
